backend:
  name: git-gateway
  branch: main    # branch to commit changes

media_folder: "assets/uploads"       # Where uploaded media files go
public_folder: "/assets/uploads"     # Public URL for media

collections:
  - name: "galleries"
    label: "Photo Galleries"
    folder: "galleries"              # Folder to store gallery entries
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Photos"
        name: "photos"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"