backend:
  name: git-gateway
  branch: main

media_folder: "images/photography"
public_folder: "/images/photography"

collections:
  - name: "photos"
    label: "Photography"
    folder: "_photos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Photo", name: "image", widget: "image"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["Landscape", "Portrait", "Street", "Nature", "Other"], required: false}
      - {label: "Featured", name: "featured", widget: "boolean", default: false, required: false}