# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: hairy-poppins/ethanhoffman.github.io
  branch: main
  identity_url: https://auth.decapbridge.com/sites/8e8779a3-6a5f-4f48-92e6-5f2e5c0425e1
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://ethanhoffman.me

collections:
  - name: "galleries"
    label: "Photo Galleries"
    folder: "galleries"              # Folder to store gallery entries
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
      - label: "Photos"
        name: "photos"
        widget: "list"
        field:
          label: "Image"
          name: "image"
          widget: "image"