local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: /assets
public_folder: /assets

collections:
  - name: galleries
    label: Galleries
    label_singular: gallery
    folder: assets/galleries
    create: true
    filter: {field: visibleInCMS, value: true}
    fields:
      - { name: title, widget: string }
      - { name: description, widget: text }
      - { name: photos, widget: list, fields: [
          { name: image, widget: image },
          { name: caption, widget: string }
        ]}
      - { name: visibleInCMS, widget: hidden, default: true }